
Type.registerNamespace('SportsLinkScript.Controls');SportsLinkScript.Controls.UserOffers=function(element){SportsLinkScript.Controls.UserOffers.initializeBase(this,[element]);var $0=this.obj.find('.cancelMatch');$0.button({text:false,icons:{primary:'ui-icon-closethick'}});$0.click(ss.Delegate.create(this,this.$1));}
SportsLinkScript.Controls.UserOffers.prototype={$1:function($p0){this.obj.attr('disabled','disabled').addClass('ui-state-disabled');var $0=$($p0.currentTarget);var $1={offerId:$0.attr('data-offerId')};$.post('/services/CancelOffer?signed_request='+SportsLinkScript.Shared.Utility.$0(),JSON.stringify($1),ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
SportsLinkScript.Shared.Utility.processResponse($p1_0);}));}}
SportsLinkScript.Controls.Players=function(element){SportsLinkScript.Controls.Players.initializeBase(this,[element]);this.$1=parseInt($('#playersPage').val());var $0=this.obj.find('.requestMatch');$0.button({text:true,icons:{secondary:'ui-icon-carat-1-e'}});$0.click(ss.Delegate.create(this,this.$2));var $1=$('#playersPrev');var $2=$('#playersNext');$1.button();$2.button();$1.click(ss.Delegate.create(this,this.$3));$2.click(ss.Delegate.create(this,this.$4));}
SportsLinkScript.Controls.Players.prototype={$1:0,$2:function($p0){var $0=$($p0.currentTarget);var $1=$('#challengeDialog');var $2=$1.find('.datepicker');var $3=$0.get(0).id;$2.datepicker('disable');$1.dialog({width:'260',height:'254',modal:true,title:$0.attr('Title'),buttons:{'Challenge!':ss.Delegate.create(this,function($p1_0){
this.$5($3);})},open:ss.Delegate.create(this,function(){
$1.find('.comments').focus();$2.datepicker('enable');})});},$3:function($p0){this.obj.attr('disabled','disabled').addClass('ui-state-disabled');var $0=$($p0.currentTarget);var $1={page:this.$1-1};$.post('/services/Players?signed_request='+SportsLinkScript.Shared.Utility.$0(),JSON.stringify($1),ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
SportsLinkScript.Shared.Utility.processResponse($p1_0);}));},$4:function($p0){this.obj.attr('disabled','disabled').addClass('ui-state-disabled');var $0=$($p0.currentTarget);var $1={page:this.$1+1};$.post('/services/Players?signed_request='+SportsLinkScript.Shared.Utility.$0(),JSON.stringify($1),ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
SportsLinkScript.Shared.Utility.processResponse($p1_0);}));},$5:function($p0){var $0=$('#challengeDialog');var $1=$0.find('.datepicker').val();var $2=$0.find('.time').val();var $3=$0.find('.ampm').val();var $4=$0.find('.comments').val();var $5=$1+' '+$2+$3;var $6=[];$0.find('.cities input').each(ss.Delegate.create(this,function($p1_0,$p1_1){
$6.add(($p1_1).value);}));var $7={date:$5,locations:$6,comments:$4,opponentId:0};SportsLinkScript.Controls.QuickMatch.doCreateMatch($0,$5,$6,$4,$p0,ss.Delegate.create(this,function(){
$0.dialog('close');}));}}
SportsLinkScript.Controls.ModuleInstance=function(element,instance){this.element=element;this.instance=instance;}
SportsLinkScript.Controls.ModuleInstance.prototype={element:null,instance:null}
SportsLinkScript.Controls.Results=function(element){SportsLinkScript.Controls.Results.initializeBase(this,[element]);$('.inputScore').click(ss.Delegate.create(this,this.$1));}
SportsLinkScript.Controls.Results.prototype={$1:function($p0){var $0=$($p0.currentTarget);var $1=$('#scoredialog');var $2=$0.siblings('.score').val();var $3=$0.siblings('.offerId').val();var $4=$0.siblings('.requestName').val();var $5=$0.siblings('.acceptName').val();$1.find('input').val('');var $6=$2.split(', ');for(var $7=0;$7<$6.length;++$7){var $8=$6[$7].split('-');$('#request'+$7).val($8[0]);$('#accept'+$7).val($8[1]);}$1.find('.requestName').html($4);$1.find('.acceptName').html($5);$1.dialog({width:'210',height:'370',modal:'true',buttons:{'Report Score':ss.Delegate.create(this,function($p1_0){
this.$2($1,$3);})}});},$2:function($p0,$p1){var $0=$('#scoreComments').val();var $1='';for(var $3=0;$3<5;++$3){var $4=$('#request'+$3).val();var $5=$('#accept'+$3).val();if(String.isNullOrEmpty($4)||String.isNullOrEmpty($5)){break;}if($1.length>0){$1=$1+', ';}$1=$1+$4+'-'+$5;}var $2={offerId:$p1,comments:$0,scores:$1};$p0.attr('disabled','disabled').addClass('ui-state-disabled');$.post('/services/PostScore?signed_request='+SportsLinkScript.Shared.Utility.$0(),JSON.stringify($2),ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
$p0.dialog('destroy');SportsLinkScript.Shared.Utility.processResponse($p1_0);}));},unload:function(){var $0=$('#scoredialog');$0.remove();SportsLinkScript.Controls.Results.callBaseMethod(this, 'unload');}}
SportsLinkScript.Controls.PotentialOffers=function(element){SportsLinkScript.Controls.PotentialOffers.initializeBase(this,[element]);var $0=this.obj.find('.acceptMatch');var $1=this.obj.find('.rejectMatch');$0.button({text:false,icons:{primary:'ui-icon-check'}});$1.button({text:false,icons:{primary:'ui-icon-closethick'}});$0.click(ss.Delegate.create(this,this.$1));$1.click(ss.Delegate.create(this,this.$2));}
SportsLinkScript.Controls.PotentialOffers.prototype={$1:function($p0){var $0=$($p0.currentTarget);var $1=$0.siblings('input').val();$.post('/services/AcceptOffer?signed_request='+SportsLinkScript.Shared.Utility.$0(),JSON.stringify({offerId:$1}),ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
$0.parent().children('a').fadeOut('slow');}));},$2:function($p0){alert('reject');}}
SportsLinkScript.Controls.Module=function(element){SportsLinkScript.Controls.Module.instances.add(new SportsLinkScript.Controls.ModuleInstance(element,this));this.$0=element;this.obj=$(element);this.needsData=element.getAttribute('data-async')==='true';if(this.needsData){this.loadingElement=document.createElement('div');this.loadingElement.className='loading';this.loadingElement.innerHTML='Loading...';$(this.loadingElement).insertAfter(this.obj.find('.data'));this.obj.find('.data').hide(0);this.loadData();}}
SportsLinkScript.Controls.Module.getModule=function(element){for(var $0=0;$0<SportsLinkScript.Controls.Module.instances.length;++$0){var $1=SportsLinkScript.Controls.Module.instances[$0];if($1.element===element){return $1.instance;}}return null;}
SportsLinkScript.Controls.Module.prototype={obj:null,$0:null,loadingElement:null,needsData:false,loadData:function(){},unload:function(){for(var $0=0;$0<SportsLinkScript.Controls.Module.instances.length;++$0){var $1=SportsLinkScript.Controls.Module.instances[$0];if($1.element===this.$0){SportsLinkScript.Controls.Module.instances.remove($1);return;}}}}
SportsLinkScript.Controls.QuickMatch=function(element){SportsLinkScript.Controls.QuickMatch.initializeBase(this,[element]);this.obj.find('.findMatch').click(ss.Delegate.create(this,this.$1));(this.obj.find('.datepicker')).datepicker();(this.obj.find('.findMatch')).button();(this.obj.find('select')).selectmenu();}
SportsLinkScript.Controls.QuickMatch.doCreateMatch=function(obj,datetime,ids,comments,opponentId,callback){var $0={date:datetime,locations:ids,comments:comments,opponentId:opponentId};obj.attr('disabled','disabled').addClass('ui-state-disabled');alert(document.getElementById('signed_request').getAttribute('value'));$.post('/services/CreateOffer?signed_request='+SportsLinkScript.Shared.Utility.$0(),JSON.stringify($0),function($p1_0,$p1_1,$p1_2){
obj.attr('disabled','').removeClass('ui-state-disabled');SportsLinkScript.Shared.Utility.processResponse($p1_0);if(null!==callback){callback.invoke();}});}
SportsLinkScript.Controls.QuickMatch.prototype={$1:function($p0){var $0=$($p0.currentTarget);var $1=$0.parents('.module').first();var $2=$1.find('.datepicker').val();var $3=$1.find('.time').val();var $4=$1.find('.ampm').val();var $5=$1.find('.comments').val();var $6=$2+' '+$3+$4;var $7=[];$1.find('.cities input').each(ss.Delegate.create(this,function($p1_0,$p1_1){
$7.add(($p1_1).value);}));SportsLinkScript.Controls.QuickMatch.doCreateMatch(this.obj,$6,$7,$5,0,null);}}
Type.registerNamespace('SportsLinkScript.Pages');SportsLinkScript.Pages._Index=function(){}
SportsLinkScript.Pages.Login=function(){}
SportsLinkScript.Pages.Login.init=function(action){var $0=action==='Login'||action==='Register';if($0){$('#main').show('fast');}window.fbAsyncInit=function(){
FB.init({appId:SportsLinkScript.Pages.Login.appId,cookie:true,status:true,xfbml:true});FB.getLoginStatus(function($p2_0){
var $2_0=$p2_0;if($2_0.status==='connected'){if(action==='Login'){$('#login').hide();window.location.href='/home/index';}else{$('#main').show('slow');}}else if($2_0.status==='notConnected'&&action!=='Register'){$('#login').hide();window.location.href='/home/register';}});FB.Event.subscribe('auth.login',function($p2_0){
var $2_0=$p2_0;if($2_0.status==='connected'){$('#login').hide();return;}if($0){SportsLinkScript.Pages.Login.accessToken=$2_0.session.access_token;var $2_1=FB.Data.query('select first_name, last_name, birthday, uid from user where uid={0}',$2_0.session.uid);$2_1.wait(SportsLinkScript.Pages.Login.processLogin);}else{$('#main').show('slow');}});return null;};var $1=document.createElement('script');$1.async=true;$1.src='/scripts/fb.js';document.getElementById('fb-root').appendChild($1);}
SportsLinkScript.Pages.Login.processLogin=function(rows){var $0=rows[0];$.post('/Services/AddUser?signed_request='+SportsLinkScript.Shared.Utility.$0(),{member:{}},function($p1_0,$p1_1,$p1_2){
var $1_0=$p1_0;var $1_1=$1_0.d;});}
Type.registerNamespace('SportsLinkScript.Shared');SportsLinkScript.Shared.SessionContext=function(){this.activeUsers=[];}
SportsLinkScript.Shared.SessionContext.prototype={familyId:0,challengId:0}
SportsLinkScript.Shared.Utility=function(){}
SportsLinkScript.Shared.Utility.$0=function(){return document.getElementById('signed_request').getAttribute('value');}
SportsLinkScript.Shared.Utility.showPlayerDetails=function(dialogContainerId,name,id){var $0=$('#'+dialogContainerId);if($0.length>0){$0.html('Loading...');$0.attr('title',name);var $1={id:id};$.post('/services/PlayerDetails?signed_request='+SportsLinkScript.Shared.Utility.$0(),JSON.stringify($1),function($p1_0,$p1_1,$p1_2){
var $1_0=($p1_0)['PlayerDetails'];$0.html($1_0);});$0.dialog({title:name,width:'340',height:'150',modal:'true'});}}
SportsLinkScript.Shared.Utility.processResponse=function(obj){var $0=ss.getKeys(obj);for(var $1=0;$1<$0.length;++$1){var $2=$0[$1];var $3='#module_'+$2;var $4=$($3);if($4.length>0){SportsLinkScript.Shared.Utility.$2($4,obj[$2]);}}}
SportsLinkScript.Shared.Utility.$1=function($p0){var $0=$p0.getAttribute('data-type');if(null!==$0){var $1=Type.parse('SportsLinkScript.Controls.'+$0);if(!ss.isNullOrUndefined($1)){new $1($p0);}}}
SportsLinkScript.Shared.Utility.$2=function($p0,$p1){var $0=$p0.children().first().get(0);var $1=SportsLinkScript.Controls.Module.getModule($0);debugger;$p0.fadeOut(500,function(){
if(null!==$1){$1.unload();}$p0.html($p1);$p0.fadeIn(500);SportsLinkScript.Shared.Utility.$1($p0.children().first().get(0));});}
Type.registerNamespace('SportsLinkScript.Shared.Facebook');SportsLinkScript.Controls.Module.registerClass('SportsLinkScript.Controls.Module');SportsLinkScript.Controls.UserOffers.registerClass('SportsLinkScript.Controls.UserOffers',SportsLinkScript.Controls.Module);SportsLinkScript.Controls.Players.registerClass('SportsLinkScript.Controls.Players',SportsLinkScript.Controls.Module);SportsLinkScript.Controls.ModuleInstance.registerClass('SportsLinkScript.Controls.ModuleInstance');SportsLinkScript.Controls.Results.registerClass('SportsLinkScript.Controls.Results',SportsLinkScript.Controls.Module);SportsLinkScript.Controls.PotentialOffers.registerClass('SportsLinkScript.Controls.PotentialOffers',SportsLinkScript.Controls.Module);SportsLinkScript.Controls.QuickMatch.registerClass('SportsLinkScript.Controls.QuickMatch',SportsLinkScript.Controls.Module);SportsLinkScript.Pages._Index.registerClass('SportsLinkScript.Pages._Index');SportsLinkScript.Pages.Login.registerClass('SportsLinkScript.Pages.Login');SportsLinkScript.Shared.SessionContext.registerClass('SportsLinkScript.Shared.SessionContext');SportsLinkScript.Shared.Utility.registerClass('SportsLinkScript.Shared.Utility');SportsLinkScript.Controls.Module.instances=[];(function(){$.ajaxSetup({contentType:'application/json; charset=utf-8',dataType:'json'});$(function(){
$('.module').each(function($p2_0,$p2_1){
SportsLinkScript.Shared.Utility.$1($p2_1);return true;});});})();
SportsLinkScript.Pages.Login.appId='197465840298266';SportsLinkScript.Pages.Login.accessToken=null;SportsLinkScript.Shared.SessionContext.instance=new SportsLinkScript.Shared.SessionContext();